// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqugxsihucjvuucgsjmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxdWd4c2lodWNqdnV1Y2dzam14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDAwMDQsImV4cCI6MjA2NTExNjAwNH0.OnRMJe7u5_S3CrlWfo_fHmkmHJ1i6lceat85cRMYzB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);